import type { Metadata } from "next";
import "./globals.css";
import { AuthProvider } from "@/store/AuthProvider";
import ReactQueryProvider from "@/store/ReactQueryProvider";
import { Toaster } from "sonner";
import { Poppins, Roboto } from "next/font/google";
import { Sidebar } from "@/components/shared";
import { TooltipProvider } from "@/components/ui/tooltip";

const poppins = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} ${roboto.variable} overflow-x-hidden`}
      >
        <ReactQueryProvider>
          <AuthProvider>
            <TooltipProvider delayDuration={200} disableHoverableContent>
              <Toaster position="top-right" />
              <main className="flex gap-x-3 relative bg-bg md:p-5 min-h-screen">
                <Sidebar />
                {children}
              </main>
            </TooltipProvider>
          </AuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
