export const Chatdata = [
  {
    unreadMessages: 2,
    userImage: "/images/dummy-user.webp",
    username: "John",
    lastMessage: "Hello!",
    lastMessageTime: "10:30 AM",
  },
  {
    unreadMessages: 0,
    userImage: "/images/dummy-user.webp",
    username: "Alice",
    lastMessage: "How are you?",
    lastMessageTime: "11:45 AM",
  },
  {
    unreadMessages: 1,
    userImage: "/images/dummy-user.webp",
    username: "Bob",
    lastMessage: "Goodbye!",
    lastMessageTime: "2:15 PM",
  },
  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },

  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },

  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },

  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },
  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },

  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },
  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },
  {
    unreadMessages: 3,
    userImage: "/images/dummy-user.webp",
    username: "Emma",
    lastMessage: "Nice to meet you!",
    lastMessageTime: "4:20 PM",
  },
  {
    unreadMessages: 0,
    userImage: "/images/dummy-user.webp",
    username: "Michael",
    lastMessage: "See you later!",
    lastMessageTime: "6:30 PM",
  },
  {
    unreadMessages: 1,
    userImage: "/images/dummy-user.webp",
    username: "Olivia",
    lastMessage: "What's up?",
    lastMessageTime: "8:45 PM",
  },
  {
    unreadMessages: 0,
    userImage: "/images/dummy-user.webp",
    username: "David",
    lastMessage: "I'm fine, thanks!",
    lastMessageTime: "9:10 PM",
  },
  {
    unreadMessages: 2,
    userImage: "/images/dummy-user.webp",
    username: "Sophia",
    lastMessage: "Have a great day!",
    lastMessageTime: "10:00 PM",
  },
  {
    unreadMessages: 0,
    userImage: "/images/dummy-user.webp",
    username: "James",
    lastMessage: "Take care!",
    lastMessageTime: "11:20 PM",
  },
  {
    unreadMessages: 1,
    userImage: "/images/dummy-user.webp",
    username: "Emily",
    lastMessage: "See you tomorrow!",
    lastMessageTime: "12:05 AM",
  },
];

export const messagesData = [
  {
    message: "Hey, how are you doing?",
    isCurrentUser: false,
    userImage: "/images/dummy-user.webp",
    sentTime: "12:00 PM",
    hasRead: false,
    hasDelivered: true,
  },
  {
    message: "Hey, how are you doing?",
    isCurrentUser: true,
    userImage: "/images/dummy-user.webp",
    sentTime: "12:00 PM",
    hasRead: false,
    hasDelivered: true,
  },
  {
    message: "I'm doing great, thanks for asking!",
    isCurrentUser: true,
    sentTime: "12:01 PM",
    hasRead: true,
    hasDelivered: true,
    userImage: "/images/dummy-user.webp",
  },
  {
    message: "Nice to meet you!",
    isCurrentUser: false,
    userImage: "/images/dummy-user.webp",
    sentTime: "12:02 PM",
    hasRead: false,
    hasDelivered: true,
  },
  {
    message: "Nice to meet you too!",
    isCurrentUser: true,
    sentTime: "12:03 PM",
    hasRead: true,
    hasDelivered: false,
    userImage: "/images/dummy-user.webp",
  },
  {
    message: "How's your day going?",
    isCurrentUser: false,
    userImage: "/images/dummy-user.webp",
    sentTime: "12:04 PM",
    hasRead: false,
    hasDelivered: true,
  },
  {
    message: "It's going well, thanks!",
    isCurrentUser: true,
    sentTime: "12:05 PM",
    hasRead: true,
    hasDelivered: true,
    userImage: "/images/dummy-user.webp",
  },
  {
    message: "What about you?",
    isCurrentUser: false,
    userImage: "/images/dummy-user.webp",
    sentTime: "12:06 PM",
    hasRead: false,
    hasDelivered: true,
  },
  {
    message: "I'm good too!",
    isCurrentUser: true,
    sentTime: "12:07 PM",
    hasRead: true,
    hasDelivered: true,
    userImage: "/images/dummy-user.webp",
  },
];
